backend:
  name: github
  repo: asarabombom-ctrl/asarabombom-ctrl.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Контент сайту"
    files:
      - label: "Головні дані"
        name: "main_data"
        file: "data.json"
        format: json
        fields:
          - {label: "Заголовок Етапу 0", name: "stage0_title", widget: "string"}
          - {label: "Фото Етапу 0", name: "stage0_image", widget: "image"}
          - {label: "Заголовок Етапу 1", name: "stage1_title", widget: "string"}
          - {label: "Фото Етапу 1", name: "stage1_image", widget: "image"}
          - {label: "Ім'я (Про мене)", name: "about_name", widget: "string"}
          - {label: "Текст (Про мене)", name: "about_bio", widget: "text"}
